### PR TITLE
add host into request's header

### PR DESCRIPTION
**Pull request by carmark**

### CODE REVIEW

**Comment by carmark** [comment]
@tardyp

**Comment by carmark** [comment]
could you please update your `buildbot` image and try it again?

**Comment by tardyp** [comment]
I am away this week. I'll work on it next Monday

**Comment by tardyp** [comment]
@carmark I just uploaded a new version to pypi

**Comment by carmark** [comment]
@tardyp Thanks, would you please update your buildbot docker image?

**Comment by tardyp** [comment]
@carmark I am finishing landing hyper support in buildbot, and as my dockerfile are depending on several projects, this is hard for me to regenerate. Do you havean urgency?

**Comment by tardyp** [comment]
@carmark just updated the docker image.

**Comment by carmark** [comment]
Thanks.

**Pull request merged**
